package com.vizuri.insurance;
import com.vizuri.insurance.domain.*;

dialect "mvel"

rule "bankruptcy"

	no-loop true
	agenda-group "eligibility"
when
	applicant : Applicant(filedForBankruptcy == true ) 
	property : Property( ) 
then	
	property.setStatus("HOLD");
	//update (property);
end

rule "fraud"

	no-loop true
	agenda-group "eligibility"
when
	applicant : Applicant(fraud == true ) 
	property : Property( ) 
then	
	property.setStatus("DISQUALIFIED");
	//update (property);
end

rule "NotRewired"

	no-loop true
	agenda-group "eligibility"
when
	property : Property(age > 80, (electrictSystemRenovated == null || electrictSystemRenovated == false )) 
then	
	property.setStatus("HOLD");
	//update (property);
end
