package com.vizuri.insurance;

import com.vizuri.insurance.domain.Applicant;
import com.vizuri.insurance.domain.Property;
import com.vizuri.insurance.domain.Quote;

dialect "mvel"

rule "bankruptcy"

	no-loop true
	agenda-group "eligibility"
when
	applicant : Applicant(filedForBankruptcy == true ) 
	$quote : Quote (id != null)
then	
	$quote.setStatus("HOLD");
	//update (property);
end

rule "fraud"

	no-loop true
	agenda-group "eligibility"
when
	applicant : Applicant(fraud == true ) 
	$quote : Quote (id != null)
then	
	$quote .setStatus("DISQUALIFIED");
	//update (property);
end

rule "NotRewired"

	no-loop true
	agenda-group "eligibility"
when
	$quote : Quote (id != null)
	property : Property(age > 80, (electrictSystemRenovated == null || electrictSystemRenovated == false )) 
then	
	$quote.setStatus("HOLD");
	//update (property);
end

rule "No showstoppers"

	no-loop true
	agenda-group "eligibility"
when
	$quote : Quote (id != null)
	applicant : Applicant(fraud == false ) 
	property : Property(age < 15, electrictSystemRenovated == true, previousClaims = false) 
then	
	$quote.setStatus("ELIGIBLE");
	//update (property);
end