package com.vizuri.insurance;
import com.vizuri.insurance.domain.*;

dialect "mvel"

rule "bankruptcy"

	no-loop true
	agenda-group "eligibility"
when
	applicant : Applicant(filedForBankruptcy == true ) 
	property : Property( ) 
then	
	property.setStatus("HOLD");
	//update (property);
end

rule "fraud"

	no-loop true
	agenda-group "eligibility"
when
	applicant : Applicant(fraud == true ) 
	property : Property( ) 
then	
	property.setStatus("DISQUALIFIED");
	//update (property);
end

rule "NotRewired"

	no-loop true
	agenda-group "eligibility"
when
	property : Property(age > 80, (electrictSystemRenovated == null || electrictSystemRenovated == false )) 
then	
	property.setStatus("HOLD");
	//update (property);
end


rule "calculateQuote"
dialect "mvel"
no-loop true
salience 1000
agenda-group "calculation"
when
	property : Property( status == "" ) 
then	
	Quote q = new Quote();
	q.setId(1);
	q.setAmount(487.95);
	property.setQuoteId(1);
	//update (property);
	insert (q);
end
/*
rule "calculateQuoteWithDogs"
dialect "mvel"
no-loop true
agenda-group "calculation"
when
	property : Property( status == "" ,dogExists == true) 
	q: Quote()
then	

	q.setAmount(686.95);
	property.setQuoteId(1);

	insert (q);
end


rule "calculateQuoteWithClaims"
dialect "mvel"
no-loop true
agenda-group "calculation"
when
	property : Property( status == "" ,previousClaims == true) 
	q: Quote()
then	

	q.setAmount(1000.95);
	property.setQuoteId(2);

	insert (q);
end
*/