package com.vizuri.insurance;

dialect "mvel"

rule "test firing agenda group: eligibility"
	agenda-group "eligibility"
when
	$answer : Answer( ) 
then
	
	System.out.println("******** Fired test rule for agenda group[eligibility]");
end

rule "bankruptcy"
	no-loop true
	agenda-group "eligibility"
when
	$quote : Quote (id != null, status != "HOLD")
	$answer : Answer(questionId == "a.filedForBankruptcy", strValue == "true" ) 
then	
	modify($quote) {setStatus("HOLD")}
end

rule "fraud"

	no-loop true
	agenda-group "eligibility"
when
	$quote : Quote (id != null)
	$answer : Answer(questionId == "a.fraud", strValue == "true" ) 
	
then		
	modify($quote) {setStatus("DISQUALIFIED")}
end

rule "NotRewired"
	no-loop true
	agenda-group "eligibility"
when
	$quote : Quote (id != null)
	property : Property(age > 80, (electrictSystemRenovated == null || electrictSystemRenovated == false )) 
then	
	modify($quote) {setStatus("HOLD")}
end

rule "old property"

	no-loop true
	agenda-group "eligibility"
when
	$quote : Quote (id != null)
	$answer : Answer(questionId == "a.fraud", strValue == "false" ) 
	$property : Property(age > 15) 
then	
	modify($quote) {setStatus("RISKY")}
end

rule "border line"

	no-loop true
	agenda-group "eligibility"
when
	$quote : Quote (id != null)
	$answer : Answer(questionId == "a.fraud", strValue == "false" ) 
	$property : Property(dogExists == true) 
then	
	modify($quote) {setStatus("TALK TO UNDERWRITER")}
end

rule "No showstoppers"
	// this rule will only be activated one
	lock-on-active true	
	agenda-group "eligibility"
when
	$quote : Quote (id != null, status != "ELIGIBLE")
	$answer_fraud : Answer(questionId == "a.fraud", strValue == "false" ) 
	$answer_bankrupt : Answer(questionId == "a.filedForBankruptcy", strValue == "false" ) 
	$property : Property(age <= 15, electrictSystemRenovated == true, previousClaims == false) 
then	
	modify($quote) {setStatus("ELIGIBLE")}
end