package com.vizuri.insurance;

import com.vizuri.insurance.domain.Applicant;
import com.vizuri.insurance.domain.Property;
import com.vizuri.insurance.domain.Quote;

dialect "mvel"

rule "test firing agenda group: eligibility"
	agenda-group "eligibility"
when
	applicant : Applicant( ) 
then
	
	System.out.println("******** Fired test rule for agenda group[eligibility]");
end

rule "bankruptcy"

	no-loop true
	agenda-group "eligibility"
when
	applicant : Applicant(filedForBankruptcy == true ) 
	$quote : Quote (id != null)
then	
	
	modify($quote) {setStatus("HOLD")}
end

rule "fraud"

	no-loop true
	agenda-group "eligibility"
when
	$quote : Quote (id != null)
	applicant : Applicant(fraud == true ) 
	
then	
	
	modify($quote) {setStatus("DISQUALIFIED")}
end

rule "NotRewired"

	no-loop true
	agenda-group "eligibility"
when
	$quote : Quote (id != null)
	property : Property(age > 80, (electrictSystemRenovated == null || electrictSystemRenovated == false )) 
then	
	$quote.setStatus("HOLD");
	modify($quote) {setStatus("HOLD")}
end

rule "No showstoppers"

	no-loop true
	agenda-group "eligibility"
when
	$quote : Quote (id != null)
	$applicant : Applicant(fraud == false ) 
	$property : Property(age < 15, electrictSystemRenovated == true, previousClaims == false) 
then	
	$quote.setStatus("ELIGIBLE");
	modify($quote) {setStatus("ELIGIBLE")}
end