package com.vizuri.insurance;

import com.vizuri.insurance.domain.Applicant;
import com.vizuri.insurance.domain.Property;
import java.util.Calendar;

rule "test firing agenda group: quote-error-check"
	agenda-group "quote-error-check"
when
	applicant : Applicant( ) 
then
	
	System.out.println("******** Fired test rule for agenda group[quote-error-check]");
end

rule "first name check"
dialect "mvel"
no-loop true
agenda-group "quote-error-check"
when
	$applicant : Applicant( firstName == null)
	
then
	QuoteMessage msg  = new QuoteMessage();
	msg.setGroup("Applicant");
	msg.setProperty("First Name");
	msg.setMessage("Applicant must have a first name");
	msg.setMessageStatus(QuoteMessageStatus.ERROR);

	insertLogical(msg);	
end;
