package com.vizuri.insurance;
import com.vizuri.insurance.domain.*;
//import com.vizuri.insurance.domain.MESSAGE_LEVEL;

rule "yearBuiltCheck"

agenda-group "Quote-Errors"
no-loop true
when
	$prop : Property( yearBuilt < 1920)
then
	QuoteMessage msg  = new QuoteMessag();
	msg.setGroup("Property");
	msg.setProperty("yearBuilt");
	msg.setMessageLevel(MESSAGE_LEVEL.ERROR);

	insertLogical(msg);
end;com.vizuri.insurance.domain.Claim( )