package com.vizuri.insurance;
import com.vizuri.insurance.domain.*;
import java.util.*;

rule "livingAreaMin"
dialect "mvel"
no-loop true
agenda-group "quote-error-check"
when
	$prop : Property( livingArea < 500)
then
	QuoteMessage msg  = new QuoteMessage();
	msg.setGroup("Property");
	msg.setProperty("livingArea");
	msg.setMessage("Living Area needs to greater than or equal to 500 sq ft.");
	msg.setMessageStatus(QuoteMessageStatus.ERROR);

	insert(msg);
end;

rule "livingAreaMax"
dialect "mvel"
no-loop true
agenda-group "quote-error-check"
when
	$prop : Property( livingArea > 5000)
then
	QuoteMessage msg  = new QuoteMessage();
	msg.setGroup("Property");
	msg.setProperty("livingArea");
	msg.setMessage("Living Area needs to less than or equal to 5000 sq ft.");
	msg.setMessageStatus(QuoteMessageStatus.ERROR);

	insert(msg);
end;

rule "roofTooOld"
dialect "mvel"
no-loop true
agenda-group "quote-error-check"
when
	property : Property(ageOfRoof >= 25 ) 
then
	QuoteMessage msg  = new QuoteMessage();
	msg.setGroup("Property");
	msg.setProperty("ageOfRoof");
	msg.setMessage("Roof Age cannot be greater than 24 years.");
	msg.setMessageStatus(QuoteMessageStatus.ERROR);

	insert(msg);
end

rule "yearBuiltCheck"
dialect "mvel"
no-loop true
agenda-group "quote-error-check"
when
	$prop : Property( yearBuilt < 1920)
then
	QuoteMessage msg  = new QuoteMessage();
	msg.setGroup("Property");
	msg.setProperty("yearBuilt");
	msg.setMessageStatus(QuoteMessageStatus.ERROR);

	insert(msg);
end;

rule "yearBuiltMax"
dialect "mvel"
no-loop true
agenda-group "quote-error-check"
when
	$prop : Property( yearBuilt > Calendar.getInstance().get(Calendar.YEAR))
then
	QuoteMessage msg  = new QuoteMessage();
	msg.setGroup("Property");
	msg.setProperty("yearBuilt");
	msg.setMessageStatus(QuoteMessageStatus.ERROR);
	msg.setMessage("Year Built cannot be greater than current year");
	insert(msg);
end;