package com.vizuri.insurance;

rule "rule1"
dialect "mvel"
when
	applicant : Applicant( firstName == "Vip" ) 
	question : Question(Id == 5)
then
	question.setEnabled( true );
	update( question );
end

rule "enableQ18"
dialect "mvel"
when
	applicant : Applicant( fraud == true ) 
	question : Question(Id == 18)
then
	question.setEnabled( true );
	update( question );
end

rule "enableQ26"
dialect "mvel"
when
	property : Property(childCareBusinessExists == true ) 
	question : Question(Id == 26)
then
	question.setEnabled( true );
	update( question );
end

rule "enableQ27"
dialect "mvel"
when
	property : Property(childCareLiabilityCoverageRequired == true ) 
	question : Question(Id == 27)
then
	question.setEnabled( true );
	update( question );
end

