package com.vizuri.insurance;

import com.vizuri.insurance.domain.Answer;
import com.vizuri.insurance.domain.Quote;
import com.vizuri.insurance.domain.ScoreCardInput;

dialect "mvel"

rule "remove any previous input facts"
	agenda-group "prepare-scorecard-input"
	salience 10
when
	$new : ScoreCardInput(updated == true ) 
	$old : ScoreCardInput(updated == false ) 
then
	$new.setUpdated(false);
	retract($old);
	System.out.println("******** remove old scorcard input");
end

rule "Set fraud as input for scorecard"
	agenda-group "prepare-scorecard-input"
	salience 0
when
	$answer : Answer( questionId == "a.fraud") 
	$sc : ScoreCardInput() 
then
	$sc.setFraud($answer.getBoolValue());
	System.out.println("******** set scorcard input: fraud: " + $answer.getBoolValue());
end

rule "Set FiledForBankrupcy as input for scorecard"
	agenda-group "prepare-scorecard-input"
	salience 0
when
	$answer : Answer( questionId == "a.filedForBankruptcy") 
	$sc : ScoreCardInput() 
then
	$sc.setFiledForBankrupcy($answer.getBoolValue());
	System.out.println("******** set scorcard input: FiledForBankrupcy: " + $answer.getBoolValue());
end