package com.vizuri.insurance;

// this is for first time inserted answers
rule "Reset answer updated flag"
agenda-group "sync-answers"
when 
	$a_new : Answer ( updatedValue == true )
	not $a_old : Answer ( questionId == $a_new.questionId, updatedValue == false)
then
	modify($a_new){ setUpdatedValue( false ) }
	System.out.println("reset answer: "+ $a_new.getQuestionId());
end;

// this is for answers that are updated for a second or more times
rule "Remove old answers"
agenda-group "sync-answers"
when 
	$a_new : Answer ( updatedValue == true)
	$a_old : Answer ( questionId == $a_old.questionId, updatedValue == false )
	
then
	// remove the old answer which was not update if we have the same answer but with an updated value
	System.out.println("remove old answer: "+ $a_old.getQuestionId());
	modify($a_new){ setUpdatedValue( false ) }
	retract( $a_old );
end

// this is for setting the question model if any answer
rule "Update question for a given answer"
	agenda-group "sync-answers"
	no-loop true
when 
	$answer : Answer ( updatedValue == false , strValue != null && strValue.isEmpty == false)
	$question : Question ( questionId == $answer.questionId, strValue != $answer.strValue)
then
	modify($question){ setStrValue( $answer.getStrValue() ) }
	System.out.println("set question["+$question.getQuestionId()+"] strValue: "+ $question.getStrValue());
end
