package com.vizuri.insurance;

// this is for first time inserted answers
rule "Reset answer updated flag"
agenda-group "reset-answers"
when 
	$a_new : Answer ( updatedValue == true )
	not $a_old : Answer ( questionId == $a_new.questionId, updatedValue == false)
then
	modify($a_new){ setUpdatedValue( false ) }
	System.out.println("reset answer: "+ $a_new.getQuestionIdentifier());
end;

// this is for answers that are updated for a second or more times
rule "Remove old answers"
agenda-group "remove-old-answers"
when 
	$a_new : Answer ( updatedValue == true)
	$a_old : Answer ( questionId == $a_old.questionId, updatedValue == false )
	
then
	// remove the old answer which was not update if we have the same answer but with an updated value
	System.out.println("remove old answer: "+ $a_old.getQuestionIdentifier());
	modify($a_new){ setUpdatedValue( false ) }
	retract( $a_old );
end;