package com.vizuri.insurance;

import com.vizuri.insurance.domain.Applicant;
import com.vizuri.insurance.domain.Property;
import java.util.Calendar;

dialect "mvel"

rule "If selected that dogs exists, but did not give details"
	no-loop true
	agenda-group "quote-error-check"
when
	property : Property(dogExists == true, dogs.size == 0 ) 
then
	QuoteMessage msg  = new QuoteMessage();
	msg.setGroup("Property");
	msg.setProperty("dogs");
	msg.setMessage("Please enter details of existing dogs");
	msg.setMessageStatus(QuoteMessageStatus.ERROR);

	insertLogical(msg);
end