{
	"applicant" : {
		"id" : null,
		"firstName" : "Arun",
		"lastName" : "Shakya",
		"fraud" : false,
		"email" : "ashakya@gmail.com",
		"phone" : "7033626250",
		"anyPreviousInsuranceDenials" : false,
		"filedForBankruptcy" : true
	},
	"questions" : [
			{
				"id" : 3,
				"description" : "Email",
				"answerType" : "String",
				"group" : "Applicant",
				"mappedObject" : "Applicant",
				"mappedProperty" : "email",
				"required" : true,
				"enabled" : true,
				"parentId" : 0
			},
			{
				"id" : 20,
				"description" : "Claim Date",
				"answerType" : "Date",
				"group" : "Property",
				"mappedObject" : "Claim",
				"mappedProperty" : "claimDate",
				"required" : false,
				"enabled" : false,
				"parentId" : 19
			},
			{
				"id" : 27,
				"description" : "Does any other applicant have child care liability coverage provided by another company?",
				"answerType" : "Boolean",
				"group" : "Property",
				"mappedObject" : "Property",
				"mappedProperty" : "childCareLiabilityAlreadyExists",
				"required" : false,
				"enabled" : false,
				"parentId" : 26
			},
			{
				"id" : 21,
				"description" : "Claim Amount",
				"answerType" : "Double",
				"group" : "Property",
				"mappedObject" : "Claim",
				"mappedProperty" : "claimAmount",
				"required" : false,
				"enabled" : false,
				"parentId" : 19
			},
			{
				"id" : 26,
				"description" : "Do you want Child Care Liability Coverage?",
				"answerType" : "Boolean",
				"group" : "Property",
				"mappedObject" : "Property",
				"mappedProperty" : "childCareLiabilityCoverageRequired",
				"required" : false,
				"enabled" : false,
				"parentId" : 25
			},
			{
				"id" : 9,
				"description" : "Zip Code",
				"answerType" : "Integer",
				"group" : "Property",
				"mappedObject" : "Address",
				"mappedProperty" : "zip",
				"required" : true,
				"enabled" : true,
				"parentId" : 0
			},
			{
				"id" : 8,
				"description" : "State",
				"answerType" : "String",
				"group" : "Property",
				"mappedObject" : "Address",
				"mappedProperty" : "state",
				"required" : true,
				"enabled" : true,
				"parentId" : 0
			},
			{
				"id" : 23,
				"description" : "Number of dogs",
				"answerType" : "Integer",
				"group" : "Property",
				"mappedObject" : "Property",
				"mappedProperty" : "dogs",
				"required" : false,
				"enabled" : false,
				"parentId" : 22
			},
			{
				"id" : 18,
				"description" : "Has any insurer or agency canceled or refused to issue or renew similar insurance to the named applicant or any household member within the past 3 years?",
				"answerType" : "Boolean",
				"group" : "Property",
				"mappedObject" : "Applicant",
				"mappedProperty" : "anyPreviousInsuranceDenials",
				"required" : true,
				"enabled" : false,
				"parentId" : 17
			},
			{
				"id" : 10,
				"description" : "When would you like your home policy to begin? ",
				"answerType" : "Date",
				"group" : "Property",
				"mappedObject" : "Property",
				"mappedProperty" : "policyBeginDate",
				"required" : true,
				"enabled" : true,
				"parentId" : 0
			},
			{
				"id" : 5,
				"description" : "Have you filed for bankruptcy in the last 1 year?",
				"answerType" : "Boolean",
				"group" : "Applicant",
				"mappedObject" : "Applicant",
				"mappedProperty" : "filedForBankruptcy",
				"required" : false,
				"enabled" : false,
				"parentId" : 1
			},
			{
				"id" : 15,
				"description" : "Has the Electric System completely renovated?",
				"answerType" : "Boolean",
				"group" : "Property",
				"mappedObject" : "Property",
				"mappedProperty" : "electrictSystemRenovated",
				"required" : true,
				"enabled" : true,
				"parentId" : 0
			},
			{
				"id" : 12,
				"description" : "Year Built",
				"answerType" : "Integer",
				"group" : "Property",
				"mappedObject" : "Property",
				"mappedProperty" : "yearBuilt",
				"required" : true,
				"enabled" : true,
				"parentId" : 0
			},
			{
				"id" : 25,
				"description" : "Is there any child care business conducted on the premises ?",
				"answerType" : "Boolean",
				"group" : "Property",
				"mappedObject" : "Property",
				"mappedProperty" : "childCareBusinessExists",
				"required" : true,
				"enabled" : true,
				"parentId" : 0
			},
			{
				"id" : 6,
				"description" : "Street Address",
				"answerType" : "String",
				"group" : "Property",
				"mappedObject" : "Address",
				"mappedProperty" : "street",
				"required" : true,
				"enabled" : true,
				"parentId" : 0
			},
			{
				"id" : 24,
				"description" : "Dog type",
				"answerType" : "String",
				"group" : "Property",
				"mappedObject" : "Property",
				"mappedProperty" : "dogs",
				"required" : false,
				"enabled" : false,
				"parentId" : 22
			},
			{
				"id" : 11,
				"description" : "What is the home puchase date?",
				"answerType" : "Date",
				"group" : "Property",
				"mappedObject" : "Property",
				"mappedProperty" : "purchaseDate",
				"required" : true,
				"enabled" : true,
				"parentId" : 0
			},
			{
				"id" : 13,
				"description" : "Approximate Living Area",
				"answerType" : "Integer",
				"group" : "Property",
				"mappedObject" : "Property",
				"mappedProperty" : "livingArea",
				"required" : true,
				"enabled" : true,
				"parentId" : 0
			},
			{
				"id" : 14,
				"description" : "Approximate age of roof",
				"answerType" : "Integer",
				"group" : "Property",
				"mappedObject" : "Property",
				"mappedProperty" : "ageOfRoof",
				"required" : true,
				"enabled" : true,
				"parentId" : 0
			},
			{
				"id" : 17,
				"description" : "Have you been convicted of arson, fraud, or other insurance related offenses?",
				"answerType" : "Boolean",
				"group" : "Applicant",
				"mappedObject" : "Applicant",
				"mappedProperty" : "fraud",
				"required" : true,
				"enabled" : true,
				"parentId" : 0
			}, {
				"id" : 2,
				"description" : "Last Name",
				"answerType" : "String",
				"group" : "Applicant",
				"mappedObject" : "Applicant",
				"mappedProperty" : "lastName",
				"required" : true,
				"enabled" : true,
				"parentId" : 0
			}, {
				"id" : 1,
				"description" : "First Name",
				"answerType" : "String",
				"group" : "Applicant",
				"mappedObject" : "Applicant",
				"mappedProperty" : "firstName",
				"required" : true,
				"enabled" : true,
				"parentId" : 0
			}, {
				"id" : 4,
				"description" : "Phone",
				"answerType" : "String",
				"group" : "Applicant",
				"mappedObject" : "Applicant",
				"mappedProperty" : "phone",
				"required" : true,
				"enabled" : true,
				"parentId" : 0
			}, {
				"id" : 22,
				"description" : "Are there any dogs?",
				"answerType" : "Boolean",
				"group" : "Property",
				"mappedObject" : "Property",
				"mappedProperty" : "dogExists",
				"required" : true,
				"enabled" : true,
				"parentId" : 0
			}, {
				"id" : 19,
				"description" : "Do you have any previous claims?",
				"answerType" : "Boolean",
				"group" : "Property",
				"mappedObject" : "Property",
				"mappedProperty" : "previousClaims",
				"required" : true,
				"enabled" : true,
				"parentId" : 0
			}, {
				"id" : 16,
				"description" : "Are there any home safety devices",
				"answerType" : "Boolean",
				"group" : "Property",
				"mappedObject" : "Property",
				"mappedProperty" : "homeSafetyDeviceInstalled",
				"required" : true,
				"enabled" : true,
				"parentId" : 0
			}, {
				"id" : 7,
				"description" : "City",
				"answerType" : "String",
				"group" : "Property",
				"mappedObject" : "Address",
				"mappedProperty" : "city",
				"required" : true,
				"enabled" : true,
				"parentId" : 0
			} ],
	"applicantQuestMap" : {
		"p.street" : {
			"id" : 6,
			"description" : "Street Address",
			"answerType" : "String",
			"group" : "Property",
			"mappedObject" : "Address",
			"mappedProperty" : "street",
			"required" : true,
			"enabled" : true,
			"parentId" : 0
		},
		"p.zip" : {
			"id" : 9,
			"description" : "Zip Code",
			"answerType" : "Integer",
			"group" : "Property",
			"mappedObject" : "Address",
			"mappedProperty" : "zip",
			"required" : true,
			"enabled" : true,
			"parentId" : 0
		},
		"a.lastName" : {
			"id" : 2,
			"description" : "Last Name",
			"answerType" : "String",
			"group" : "Applicant",
			"mappedObject" : "Applicant",
			"mappedProperty" : "lastName",
			"required" : true,
			"enabled" : true,
			"parentId" : 0
		},
		"p.childCareLiabilityCoverageRequired" : {
			"id" : 26,
			"description" : "Do you want Child Care Liability Coverage?",
			"answerType" : "Boolean",
			"group" : "Property",
			"mappedObject" : "Property",
			"mappedProperty" : "childCareLiabilityCoverageRequired",
			"required" : false,
			"enabled" : false,
			"parentId" : 25
		},
		"a.email" : {
			"id" : 3,
			"description" : "Email",
			"answerType" : "String",
			"group" : "Applicant",
			"mappedObject" : "Applicant",
			"mappedProperty" : "email",
			"required" : true,
			"enabled" : true,
			"parentId" : 0
		},
		"p.livingArea" : {
			"id" : 13,
			"description" : "Approximate Living Area",
			"answerType" : "Integer",
			"group" : "Property",
			"mappedObject" : "Property",
			"mappedProperty" : "livingArea",
			"required" : true,
			"enabled" : true,
			"parentId" : 0
		},
		"p.previousClaims" : {
			"id" : 19,
			"description" : "Do you have any previous claims?",
			"answerType" : "Boolean",
			"group" : "Property",
			"mappedObject" : "Property",
			"mappedProperty" : "previousClaims",
			"required" : true,
			"enabled" : true,
			"parentId" : 0
		},
		"a.phone" : {
			"id" : 4,
			"description" : "Phone",
			"answerType" : "String",
			"group" : "Applicant",
			"mappedObject" : "Applicant",
			"mappedProperty" : "phone",
			"required" : true,
			"enabled" : true,
			"parentId" : 0
		},
		"p.yearBuilt" : {
			"id" : 12,
			"description" : "Year Built",
			"answerType" : "Integer",
			"group" : "Property",
			"mappedObject" : "Property",
			"mappedProperty" : "yearBuilt",
			"required" : true,
			"enabled" : true,
			"parentId" : 0
		},
		"p.policyBeginDate" : {
			"id" : 10,
			"description" : "When would you like your home policy to begin? ",
			"answerType" : "Date",
			"group" : "Property",
			"mappedObject" : "Property",
			"mappedProperty" : "policyBeginDate",
			"required" : true,
			"enabled" : true,
			"parentId" : 0
		},
		"a.fraud" : {
			"id" : 17,
			"description" : "Have you been convicted of arson, fraud, or other insurance related offenses?",
			"answerType" : "Boolean",
			"group" : "Applicant",
			"mappedObject" : "Applicant",
			"mappedProperty" : "fraud",
			"required" : true,
			"enabled" : true,
			"parentId" : 0
		},
		"p.state" : {
			"id" : 8,
			"description" : "State",
			"answerType" : "String",
			"group" : "Property",
			"mappedObject" : "Address",
			"mappedProperty" : "state",
			"required" : true,
			"enabled" : true,
			"parentId" : 0
		},
		"p.childCareLiabilityAlreadyExists" : {
			"id" : 27,
			"description" : "Does any other applicant have child care liability coverage provided by another company?",
			"answerType" : "Boolean",
			"group" : "Property",
			"mappedObject" : "Property",
			"mappedProperty" : "childCareLiabilityAlreadyExists",
			"required" : false,
			"enabled" : false,
			"parentId" : 26
		},
		"p.city" : {
			"id" : 7,
			"description" : "City",
			"answerType" : "String",
			"group" : "Property",
			"mappedObject" : "Address",
			"mappedProperty" : "city",
			"required" : true,
			"enabled" : true,
			"parentId" : 0
		},
		"p.ageOfRoof" : {
			"id" : 14,
			"description" : "Approximate age of roof",
			"answerType" : "Integer",
			"group" : "Property",
			"mappedObject" : "Property",
			"mappedProperty" : "ageOfRoof",
			"required" : true,
			"enabled" : true,
			"parentId" : 0
		},
		"p.dogs" : {
			"id" : 24,
			"description" : "Dog type",
			"answerType" : "String",
			"group" : "Property",
			"mappedObject" : "Property",
			"mappedProperty" : "dogs",
			"required" : false,
			"enabled" : false,
			"parentId" : 22
		},
		"a.firstName" : {
			"id" : 1,
			"description" : "First Name",
			"answerType" : "String",
			"group" : "Applicant",
			"mappedObject" : "Applicant",
			"mappedProperty" : "firstName",
			"required" : true,
			"enabled" : true,
			"parentId" : 0
		},
		"p.anyPreviousInsuranceDenials" : {
			"id" : 18,
			"description" : "Has any insurer or agency canceled or refused to issue or renew similar insurance to the named applicant or any household member within the past 3 years?",
			"answerType" : "Boolean",
			"group" : "Property",
			"mappedObject" : "Applicant",
			"mappedProperty" : "anyPreviousInsuranceDenials",
			"required" : true,
			"enabled" : false,
			"parentId" : 17
		},
		"p.claimAmount" : {
			"id" : 21,
			"description" : "Claim Amount",
			"answerType" : "Double",
			"group" : "Property",
			"mappedObject" : "Claim",
			"mappedProperty" : "claimAmount",
			"required" : false,
			"enabled" : false,
			"parentId" : 19
		},
		"a.filedForBankruptcy" : {
			"id" : 5,
			"description" : "Have you filed for bankruptcy in the last 1 year?",
			"answerType" : "Boolean",
			"group" : "Applicant",
			"mappedObject" : "Applicant",
			"mappedProperty" : "filedForBankruptcy",
			"required" : false,
			"enabled" : false,
			"parentId" : 1
		},
		"p.claimDate" : {
			"id" : 20,
			"description" : "Claim Date",
			"answerType" : "Date",
			"group" : "Property",
			"mappedObject" : "Claim",
			"mappedProperty" : "claimDate",
			"required" : false,
			"enabled" : false,
			"parentId" : 19
		},
		"p.dogExists" : {
			"id" : 22,
			"description" : "Are there any dogs?",
			"answerType" : "Boolean",
			"group" : "Property",
			"mappedObject" : "Property",
			"mappedProperty" : "dogExists",
			"required" : true,
			"enabled" : true,
			"parentId" : 0
		},
		"p.electrictSystemRenovated" : {
			"id" : 15,
			"description" : "Has the Electric System completely renovated?",
			"answerType" : "Boolean",
			"group" : "Property",
			"mappedObject" : "Property",
			"mappedProperty" : "electrictSystemRenovated",
			"required" : true,
			"enabled" : true,
			"parentId" : 0
		},
		"p.childCareBusinessExists" : {
			"id" : 25,
			"description" : "Is there any child care business conducted on the premises ?",
			"answerType" : "Boolean",
			"group" : "Property",
			"mappedObject" : "Property",
			"mappedProperty" : "childCareBusinessExists",
			"required" : true,
			"enabled" : true,
			"parentId" : 0
		},
		"p.homeSafetyDeviceInstalled" : {
			"id" : 16,
			"description" : "Are there any home safety devices",
			"answerType" : "Boolean",
			"group" : "Property",
			"mappedObject" : "Property",
			"mappedProperty" : "homeSafetyDeviceInstalled",
			"required" : true,
			"enabled" : true,
			"parentId" : 0
		},
		"p.purchaseDate" : {
			"id" : 11,
			"description" : "What is the home puchase date?",
			"answerType" : "Date",
			"group" : "Property",
			"mappedObject" : "Property",
			"mappedProperty" : "purchaseDate",
			"required" : true,
			"enabled" : true,
			"parentId" : 0
		}
	},
	"propertyQuestMap" : {},
	"property" : {
		"address" : {
			"street" : "5159 WOODFIELD DR",
			"city" : "CENTREVILLE",
			"state" : "VA - Virginia",
			"zip" : "201204124",
			"verified" : false
		},
		//"policyBeginDate" : "03/22/2015",
		//"purchaseDate" : "03/22/2015",
		"yearBuilt" : 2012,
		"livingArea" : 0,
		"ageOfRoof" : 0,
		"electrictSystemRenovated" : false,
		"homeSafetyDeviceInstalled" : false,
		"homeSafetyDevices" : null,
		"previousClaims" : false,
		"claims" : [],
		"dogExists" : false,
		"dogs" : null,
		"childCareBusinessExists" : false,
		"childCareLiabilityCoverageRequired" : false,
		"childCareLiabilityAlreadyExists" : false,
		"applicantId" : null,
		"policyId" : null,
		"quoteId" : null,
		"status" : "",
		"age" : 3
	},
	"quote" : null
}